### ISSUE TITLE
[Feature request] Link to remote repository after successful pushing

### ISSUE THREAD

**Issue by Kristinita** [silentninja/easygit#5]
After push, I often need to go in my remote repository, that I can see my changes.

For example, when I make a push via [Git](https://packagecontrol.io/packages/Git) plugin, after successful pushing console appears:

![Easygit](http://i.imgur.com/Qv1Jy8r.png)

I can to go in https://github.com/Kristinita/Kristinita.github.io.git.

Is it possible to do the same in Easygit?

Thanks.

**Comment by silentninja** [comment]
I don't use sublime text anymore. Wont be working on new features anytime soon sorry. Feel free to fork it and start a new project
